#include "../v7/model.h"
#include "../v7/pool.h"
#include <random>
using namespace v2;
struct E{Board b;double target;int split=0,weight=1;};
int main(int argc,char**argv){try{uint32_t first=argc>1?std::stoul(argv[1]):9710001;init();Learner base;base.load("training/v7/base.ntd");std::vector<E> teacher,td;std::ifstream f("training/diagnosis-v7/fit-data.txt");int source,d;E e;while(f>>source>>d>>e.weight>>e.split>>e.target){for(auto&r:e.b){int n;f>>n;r=n;}if(!f)throw std::runtime_error("data");teacher.push_back(e);}int resumed=0;for(int i=0;i<100;i++){RNG rng{uint32_t(first+i)};Game g;g.reset(rng);std::vector<ScoreRecord> t;double last=0;int steps=0;bool success=false;while(!g.over&&steps<6000){auto a=policyTwo(g,base);if(!t.empty())t.back().reward=last+a.reward;if(high(a.b)>=12){t.push_back({a.b,base.value(a.b,stage(a.b)),0,true});success=true;break;}t.push_back({a.b,base.value(a.b,0),0,false});last=g.advance(a,rng);steps++;}if(!success&&!g.over)throw std::runtime_error("truncated");if(!success&&!t.empty())t.back().reward=last;for(size_t j=0;j<t.size();j++)if(!t[j].boundary)td.push_back({t[j].board,lambdaTarget(t,j),0,1});}
 std::vector<int> teachOrder;for(int i=0;i<int(teacher.size());i++)if(!teacher[i].split)for(int w=0;w<teacher[i].weight;w++)teachOrder.push_back(i);std::ofstream out(argc>2?argv[2]:"training/diagnosis-v7/interference.jsonl");out<<std::setprecision(17);
 for(int seed: {202609221,202609222,202609223}){Learner initial=base;std::mt19937 warm(seed);auto ord=teachOrder;for(int epoch=0;epoch<100;epoch++){std::shuffle(ord.begin(),ord.end(),warm);for(int i:ord)initial.update(teacher[i].b,teacher[i].target,.01);}for(double ratio: {0.,.0021,.02,.1}){Learner m=initial;std::mt19937 trng(seed^0x7854),drng(seed^0x6543);std::vector<int> idx(td.size());std::iota(idx.begin(),idx.end(),0);uint64_t updates=0,teacherUpdates=0;auto emit=[&](int epoch){double sq[2]{};int n[2]{};for(auto&e:teacher){double d=m.value(e.b,0)-e.target;sq[e.split]+=d*d;n[e.split]++;}out<<"{\"seed\":"<<seed<<",\"ratio\":"<<ratio<<",\"epoch\":"<<epoch<<",\"TDExamples\":"<<td.size()<<",\"resumedGames\":"<<resumed<<",\"TDUpdates\":"<<updates<<",\"teacherUpdates\":"<<teacherUpdates<<",\"rmse\":["<<std::sqrt(sq[0]/n[0])<<','<<std::sqrt(sq[1]/n[1])<<"]}"<<std::endl;};emit(0);for(int epoch=1;epoch<=5;epoch++){std::shuffle(idx.begin(),idx.end(),drng);for(int i:idx){m.update(td[i].b,td[i].target,.003);updates++;while(teacherUpdates<uint64_t(updates*ratio)){auto&e=teacher[teachOrder[trng()%teachOrder.size()]];m.update(e.b,e.target,.001);teacherUpdates++;}}emit(epoch);}for(int s=1;s<3;s++)if(m.base.w[s]!=base.base.w[s])throw std::runtime_error("late stage changed");}}
}catch(const std::exception&e){std::cerr<<e.what()<<std::endl;return 1;}}
