from pathlib import Path
import json
p=Path('training/v9'); r=json.loads((p/'results.json').read_text()); names={'board_value':'棋盘＋价值','context_value':'完整公开信息＋价值','board_joint':'棋盘＋价值和策略','context_joint':'完整公开信息＋价值和策略'}
lines=['# V9：公开信息与策略学习的四组对照','', '本轮是完整四层搜索的监督蒸馏实验，尚不是反复自我对弈、重新采样和更新的闭环强化学习。目标是检验两项改动：补充公开状态，以及联合学习动作策略。','', '## 设计','', '来自 1200 局的 4866 个教师局面，包含成功和失败对局。按源对局划分 960 局训练、240 局验证；对应 3891 / 975 个局面。全量四层 expectimax 产生价值标签，温度 2000 的 softmax 产生动作软标签（不是 MCTS 访问次数）。验证两侧没有 D4 等价棋盘交叉。','', '四组各训练三个独立初始化／打乱种子，使用相同教师数据。32 单元 ReLU 残差网络、30 轮训练，在新开局评估前按验证损失锁定权重。所有模型和未改动 MCTS 基线每步采用 1 ms CPU 软预算、最多八层搜索，各跑相同的 512 个新开局种子，达到 1536 或死亡即停。共 6656 次运行，初始种子仍只有 512 个。','', '## 达到 1536 的结果','', '| 方案 | 训练种子 1 | 训练种子 2 | 训练种子 3 | 平均成功率 | 每步模拟次数 |','|---|---:|---:|---:|---:|---:|']
b=r['baseline'];lines.append(f"| 未改动 MCTS | {b['successCounts'][0]}/512 | — | — | {b['meanRatePercent']:.2f}% | {b['simulationsPerMove']:.1f} |")
for a,d in r['arms'].items():
 counts=' | '.join(f'{n}/512' for n in d['successCounts']); lines.append(f"| {names[a]} | {counts} | {d['meanRatePercent']:.2f}% | {d['simulationsPerMove']:.1f} |")
lines+=['', '**结论：本轮未超过未改动 MCTS，不升级网页默认 AI。** 四组的三个种子均低于本次基线。联合训练策略的平均主效应为正但区间跨零，补充公开信息也没有稳定收益。验证误差改善没有转化为实战改善。', '', '新网络推理后，每步搜索量由约 608 次降到 319–361 次。计算成本是可能原因，但本轮没有固定模拟次数对照，不能据此确认它是主因。价值修正同时改变了搜索叶节点的估值，教师是四层分数目标而非直接的 1536 成功目标，这些因素尚未被拆开。', '', '下一步优先做因果拆分：① 保留原价值，仅使用策略头；② 保留原策略先验，仅加入价值修正；③ 原方案与候选同时做固定模拟次数和固定时间对照。候选应事先按验证集选定，不按此次实战最高分挑选。先确定是推理成本、价值修正还是策略先验造成差异，再决定是否增加训练规模。', '', '## 预先指定的主效应','', '对每个新开局，先在三个训练种子和另一因素的两组上求平均，再计算成对差值。置信区间和检验以 512 个开局种子为聚类单位；两个主效应的 p 值用 Holm 校正。区间条件于本次三个训练种子，不能代表全部训练随机性的区间。','', '| 主效应 | 成功率差（百分点） | 95% 区间 | Holm p |','|---|---:|---:|---:|']
for k,label in [('context','补充公开信息'),('policy','联合学习策略')]:
 d=r['factorial'][k];lo,hi=d['CI95PP'];lines.append(f"| {label} | {d['differencePP']:+.2f} | [{lo:+.2f}, {hi:+.2f}] | {d['holmP']:.4f} |")
lines+=['', '各组与基线的比较属于探索性结果，不据此挑选检查点或直接上线。完整对比及交互效应见 `training/v9/results.json`。','', '## 学习与计算代价','',f"初始模型验证 RMSE 为 {r['initialValidation']['validationRMSE']:.0f}，策略 KL 为 {r['initialValidation']['validationKL']:.4f}。",'', '| 方案 | 验证 RMSE | 验证策略 KL | 平均每步 CPU（毫秒） | 超过预算 20% 的步数占比 |','|---|---:|---:|---:|---:|']
for a,d in r['arms'].items():
 v=d['validationMean'];lines.append(f"| {names[a]} | {v['validationRMSE']:.0f} | {v['validationKL']:.4f} | {d['cpuMsPerMove']:.3f} | {d['overrun20PercentMoves']:.2f}% |")
lines += ['',f"未改动基线平均每步 {b['cpuMsPerMove']:.3f} ms。计时为软预算：基线最慢单步 {b['maxMoveCPUms']:.2f} ms，候选最慢单步 {max(d['maxMoveCPUms'] for d in r['arms'].values()):.2f} ms；不作硬实时承诺。",'', '## 边界与复现','', '- 本次没有测量 6144 成功率，也没有浏览器端验证；网页保持上一版。','- 候选增加网络推理成本，因此相同时间内搜索次数会变化。本实验测量两项改动在固定计算预算下的总体效果；不能单独归因于模型精度。','- 三个训练种子共用教师数据；没有测量重新采集教师数据带来的方差。','- 游戏随机源和搜索随机源分离，但策略走向不同后，同种子不等于完全相同的后续来牌位置。','- CPU 计时搜索受机器速度影响，重新运行不保证逐局结果完全一致。','- 20 个零残差模型与原 MCTS 固定模拟数的一致性检查、MLP 梯度检查和 D4 坐标检查已通过。','', '代码、12 份模型、逐局结果、验证日志、冻结权重哈希和复现命令均在 `training/v9/`；见 `README.md`、`protocol.json`、`manifest.json`。']
Path('RL-V9-ABLATION.md').write_text('\n'.join(lines)+'\n')
